// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: crypto_address.sql

package db_test

import (
	"context"
)

const findCryptoAddressByAddress = `-- name: FindCryptoAddressByAddress :one
SELECT id, address, coin, is_occupied, user_id FROM crypto_addresses
WHERE address = $1
`

func (q *Queries) FindCryptoAddressByAddress(ctx context.Context, address string) (CryptoAddress, error) {
	row := q.db.QueryRow(ctx, findCryptoAddressByAddress, address)
	var i CryptoAddress
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Coin,
		&i.IsOccupied,
		&i.UserID,
	)
	return i, err
}
