// Code generated by mockery v2.50.4. DO NOT EDIT.

package listener

import mock "github.com/stretchr/testify/mock"

// MockSharedBlock is an autogenerated mock type for the SharedBlock type
type MockSharedBlock struct {
	mock.Mock
}

// GetTxHashes provides a mock function with no fields
func (_m *MockSharedBlock) GetTxHashes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxHashes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewMockSharedBlock creates a new instance of MockSharedBlock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSharedBlock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSharedBlock {
	mock := &MockSharedBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
